spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/junit_db2
    username: db_user1
    password: 12345
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
  sql:
    show: true
